server:
  port: 8888
  servlet:
    context-path: /mooc
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mooc?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456